import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth/next"
import Provider from '@/components/context/client-provider'
import { authOptions } from '../utils/authOptions'
import { ProviderStore } from '@/redux/provider'
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className="bg-white">
        <ProviderStore>
          <Provider session={session}>
            <Header />
            {children}
            <Footer />
          </Provider>
        </ProviderStore>
      </body>
    </html>
  );
}
